FROM ghcr.io/requarks/wiki:2

COPY modules/authentication/ietf /wiki/server/modules/authentication/ietf
COPY modules/rendering/html-ietf-custom /wiki/server/modules/rendering/html-ietf-custom

ENV DB_TYPE=postgres
